source:
  - name: source.tar.gz
    url: https://github.com/gohugoio/hugo/archive/refs/tags/v0.148.2.tar.gz
    sha256sum: 562024495bb23ee54d11bbb63d15156213d40b24c5f5276bc8851dc6135b8602
hooks:
  universal:
    check: github-release
