package: hugo
source:
  - name: source.tar.gz
    url: https://github.com/gohugoio/hugo/archive/refs/tags/v0.149.0.tar.gz
    sha256sum: 2e8058ea2cf66b4935c8f4269fcc728efe4106f8bff034c0bd092f8cb4d607bb
# matrix:
#   - distro: opensuse
#     branch: "15.6"
#     image: opensuse/leap:15.6

#   - distro: fedora
#     branch: "43"
#     image: fedora:43
hooks:
  universal:
    check: github-release
