source:
  - name: source.tar.gz
    url: https://github.com/gohugoio/hugo/archive/refs/tags/v0.149.1.tar.gz
    sha256sum: 4ea9e45160004b3824a7aa82d594120966c596c161cc27621000b0e0af7f11ae
hooks:
  universal:
    check: github-release
