source:
  - name: source.tar.gz
    url: https://github.com/gohugoio/hugo/archive/refs/tags/v0.148.2.tar.gz
    sha256sum: 562024495bb23ee54d11bbb63d15156213d40b24c5f5276bc8851dc6135b8602

matrix:
  - distro: opensuse
    branch: "15.6"
    image: opensuse/leap:15.6

  - distro: fedora
    branch: "43"
    image: fedora:43

hooks:
  disable_global:
    - prebuild   # 禁用全局 prebuild 阶段的 hook
    - cache      # 禁用全局 cache 阶段的 hook（未来可能用到）

  universal:
    check: github-release
    pre_global_prebuild:
      - scripts/uni_before_global_prebuild.sh
    post_global_prebuild:
      - scripts/uni_after_global_prebuild.sh
    pre_global_postbuild:
      - scripts/uni_before_global_postbuild.sh
    post_global_postbuild:
      - scripts/uni_after_global_postbuild.sh

  specific:
    - distro: opensuse
      branch: tumbleweed
      pre_global_prebuild:
        - scripts/suse_before_global_prebuild.sh
      post_global_prebuild:
        - scripts/suse_after_global_prebuild.sh
      pre_global_postbuild:
        - scripts/suse_before_global_postbuild.sh
      post_global_postbuild:
        - scripts/suse_after_global_postbuild.sh
