source:
  - name: font.tar.gz
    regex: 'lxgw-wenkai-v.+\.tar\.gz'
    url: https://github.com/lxgw/LxgwWenKai/releases/download/v1.520/lxgw-wenkai-v1.520.tar.gz
    sha256sum: f069bccc54392186ae48f676ecc73964b71f28ef740b6e75231a90946fe396b1
hooks:
  universal:
    check: github-release
  specific:
    - distro: opensuse
      branch: "15.6"
      pre_global_prebuild:
        - suse-font-deps
    - distro: fedora
      branch: "42"
      pre_global_prebuild:
        - dnf-font-deps
    - distro: openeuler
      branch: "24.03"
      pre_global_prebuild:
        - dnf-font-deps
