name: Build RPMs on push
on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false # The new instance will wait for the old instance to complete

jobs:
  job1:
    uses: anm1n/yum2/.github/workflows/rpmbuild.yml@main
    with:
      root-dir: projects
      rclone-repo-name: test
      metadata-workflow-name: metadata.yml
      matrix-file: matrix.yml
      hostname: Build-Test
      build-srpm: true
      hooks-dir: hooks
    secrets:
      RCLONE_CONFIG_SECTION: ${{ secrets.RCLONE_CONFIG_SECTION }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      TOKEN: ${{ secrets.PAT }}
    permissions:
      actions: write # so we can dispatch sub workflow
      contents: read
